[phases.setup]
commands = [
  "pip install -r requirements.txt"
]

[start]
commands = [
  "langflow run",
  "streamlit run ğŸ _Dashboard.py"
]

# You can also define environment variables if needed
[env]
ENV_VAR_NAME = "value"